version: '3.8'

services:
  web:
    image: ancy
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - .:/usr/src/app
    networks:
      - api-network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DBNAME}
      - PGUSER=${POSTGRES_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - api-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
    postgres_data:

networks:
  api-network:
    driver: bridge